pandawa.workflow.event_subscriber:
    class: "%workflow.subscriber%"
    alias:
        - Symfony\Component\EventDispatcher\EventSubscriberInterface
        - workflow_subscriber

pandawa.workflow.registry:
    class: "%workflow.registry%"
    alias: Pandawa\Workflow\Registry\WorkflowRegistryInterface
    arguments:
        - "%workflow.workflows%"
        - '@workflow_subscriber'
