pandawa.workflow.event_subscriber:
    class: "%modules.workflow.subscriber%"
    alias:
        - Symfony\Component\EventDispatcher\EventSubscriberInterface
        - workflow_subscriber

pandawa.workflow.registry:
    class: "%modules.workflow.registry%"
    alias: Pandawa\Workflow\Registry\WorkflowRegistryInterface
    arguments:
        - "%modules.workflow.workflows%"
        - '@workflow_subscriber'
        - '@Pandawa\Component\Resource\ResourceRegistryInterface'
